### ISSUE TITLE
No module named 'mmdetection.mmdet.models.utils.camera'

### ISSUE THREAD

**Issue by seonghyunkim1212** [JiangWenPL/multiperson#13]
HI! Awesome work!

This is an error with evaluation code.

Traceback (most recent call last):
  File "tools/full_eval.py", line 35, in <module>
    from mmdetection.mmdet.core.utils.eval_utils import H36MEvalHandler, EvalHandler, PanopticEvalHandler, \
  File "/home/seonghyun/CRMH_venv/multiperson-master/mmdetection/mmdet/core/utils/eval_utils.py", line 7, in <module>
    from mmdetection.mmdet.models.utils.camera import PerspectiveCamera
ModuleNotFoundError: No module named 'mmdetection.mmdet.models.utils.camera'

and

Traceback (most recent call last):
  File "tools/full_eval.py", line 35, in <module>
    from mmdetection.mmdet.core.utils.eval_utils import H36MEvalHandler, EvalHandler, PanopticEvalHandler, \
  File "/home/seonghyun/CRMH_venv/multiperson-master/mmdetection/mmdet/core/utils/eval_utils.py", line 5, in <module>
    from mmdetection.mmdet.models.utils.pose_utils import reconstruction_error, vectorize_distance
ImportError: cannot import name 'vectorize_distance' from 'mmdetection.mmdet.models.utils.pose_utils' (/home/seonghyun/CRMH_venv/multiperson-master/mmdetection/mmdet/models/utils/pose_utils.py)

Where can I find these modules?
Not all code has been released yet?

**Comment by Sicanno** [comment]
Hello, I also get an error in the demo code. There seems to import  ".so" file. But it also failed when I got ".so" file which came from "setup.py" in "/mmdetection/mmdet/ops/dcn/". Is there any solution?Thanks a lot.

Traceback (most recent call last):
File "/multiperson/mmdetection/mmdet/ops/dcn/functions/deform_conv.py", line 5, in <module>
    from .. import deform_conv_cuda
ImportError: cannot import name 'deform_conv_cuda' from 'mmdetection.mmdet.ops.dcn' (/multiperson/mmdetection/mmdet/ops/dcn/__init__.py)

**Comment by nicolasugrinovic** [comment]
@seonghyunkim1212 Could you find a way around this?

**Comment by Aaron20127** [comment]
I have the same problem.

**Comment by colincqian** [comment]
Is there any update on this issue? I have the same problem @seonghyunkim1212 @nicolasugrinovic @Aaron20127

**Comment by JiangWenPL** [comment]
Should be resolved now.
