### ISSUE TITLE
Will the version of SMPL-X affect the program?

### ISSUE THREAD

**Issue by Aaron20127** [JiangWenPL/multiperson#15]
When I run the demo with the  default version of smpl-x, I encountered an error - 'no model named ModelOutput'. So I rolled back the version to 0.1.15. The demo.py then ran smoothly. But I found a slight difference between the output of the demo picture and the output of the first picture in the paper. I don't know why it is different.

**Comment by Frank-Dz** [comment]
Same question:
https://github.com/JiangWenPL/multiperson/issues/25#issue-808330751

**Comment by Frank-Dz** [comment]
> When I run the demo with the default version of smpl-x, I encountered an error - 'no model named ModelOutput'. So I rolled back the version to 0.1.15. The demo.py then ran smoothly. But I found a slight difference between the output of the demo picture and the output of the first picture in the paper. I don't know why it is different.

Hi I switch to the 0.1.15 the demo codes still can not work for me.

**Comment by Anirudh257** [comment]
@Frank-Dz I am not sure where things might have gone wrong. I have installed in python3.7 version and smplx is 0.1.24. I noticed that you have installed in the anaconda virtual environment. I have installed all my libraries in a python virtual environment. Installing it again in a normal virtual environment might solve your issues. :)

**Comment by Frank-Dz** [comment]
> @Frank-Dz I am not sure where things might have gone wrong. I have installed in python3.7 version and smplx is 0.1.24. I noticed that you have installed in the anaconda virtual environment. I have installed all my libraries in a python virtual environment. Installing it again in a normal virtual environment might solve your issues. :)

solved by modifying the code:
multiperson/mmdetection/mmdet/models/utils/smpl/smpl.py", line 64, 
```
    output = ModelOutput(vertices=smpl_output.vertices...
```
to
```
 output = SMPLXOutput(vertices=smpl_output.vertices...
```
