### ISSUE TITLE
How to use opencv calibration parameter in neural mesh render with K,R,t?

### ISSUE THREAD

**Issue by sunshinnnn** [JiangWenPL/multiperson#19]
Hi, I want to use ordinary calibration camera parameters in the differentiable render, but I find it is non-trival to direct use K, R, t which are obtained from calibration camera parameters.

**Comment by JiangWenPL** [comment]
Well, I didn't see any relationship between your question and our repo. But of course you can set K, R, t for neural renderer.

**Comment by sunshinnnn** [comment]
Well...Since your repo gives a modified version of NMR, namely you add a projection of render. However, I find using the K,R,t from camera calibration parameters will not outputs results as other renderer(Blender, or [u,v,1] = Px) results.(I guess your R,R,t may in a new coordinate(which is not the same as a OpenGL coordinate) or you may have normalized K or something else). In a word, the projection of NMR is x'P' not Px as you writen in your code, I can not render iamges as [u,v,1]=Px  projection.

**Comment by sunshinnnn** [comment]
Sorry, maybe I should pay more attention to debug the NMR or give issue in the NMR repo. Thanks all the same. 😄
