### ISSUE TITLE
Person Translation Deduction 

### ISSUE THREAD

**Issue by FishWoWater** [JiangWenPL/multiperson#22]
https://github.com/JiangWenPL/multiperson/blob/4d3dbae945e22bb1e270521b061a837976699685/mmdetection/mmdet/models/losses/smpl_loss.py#L171 to https://github.com/JiangWenPL/multiperson/blob/4d3dbae945e22bb1e270521b061a837976699685/mmdetection/mmdet/models/losses/smpl_loss.py#L176

Could you give a brief explanation about L171 to L176?  It's an approximation that depth d = 2 * focal_length / (s * max(box_w, box_h)), right?  Because generally small person means larger depth.

**Comment by JiangWenPL** [comment]
Yes, in fact it was discussed in the [supplementary](https://jiangwenpl.github.io/multiperson/files/multiperson-supp.pdf).
