### ISSUE TITLE
h36m_single_train_openpose.npz

### ISSUE THREAD

**Issue by Sicanno** [JiangWenPL/multiperson#24]
Hi, I found the above file is lost, where can I get it?

**Comment by Sicanno** [comment]
Is there any solution to generate it?

**Comment by nicolasugrinovic** [comment]
You should check  https://github.com/nkolot/SPIN/issues/20, here the code it refers to mosh data meaning that it has smpl parameters on it. Also, I think this should also contain CMU and the PosePrior datasets from AMASS. 
Cheers
