### ISSUE TITLE
J_regressor_extra vs J_regressor_h36m

### ISSUE THREAD

**Issue by kidkych** [JiangWenPL/multiperson#35]
What is the difference between the two joint regressors? From what I can tell J_regressor_extra is used to extract smpl paramters during smplifyx fitting operation for dataset generation, while J_regressor_h36m is used solely in loss calculation.

Since J_regressor_extra is used to fit SMPL keypoints to gt keypoints would it not also work for loss calculation?

**Comment by JiangWenPL** [comment]
I guess that was just related to the legacy code from HMR and SPIN. There might be slight difference on the definition of joints across different dataset, even though they have the same name.
