### ISSUE TITLE
Speed for fitting SMPL-X to 3D key points

### ISSUE THREAD

**Issue by ZhengyiLuo** [JiangWenPL/multiperson#8]
Hi, 

Thanks a ton for the great work! 

I am trying out the script to fit SMPL-X to 3D keypoints and are noticing a speed of about 40 secs per frame; This is rather slow even with parallelzation. Any suggestions?

**Comment by Sicanno** [comment]
Hi, I get the same problem. By the way, how do we get the 'data/h36m/extras/h36m_single_train_openpose.npz', just translate this .pkl file into the .npz? Because it seems that only the pose and shape parameters of 3.6m has been used.

**Comment by Sicanno** [comment]
Also, the loss of idx 15635 is nan. Maybe it will cause some error.

**Comment by tiangexiang** [comment]
Hi, do you guys solve the speed problem?

**Comment by ZhengyiLuo** [comment]
@tiangexiang  This repo has the fitted H36M from this method available for download: https://github.com/mks0601/I2L-MeshNet_RELEASE

**Comment by tiangexiang** [comment]
@ZhengyiLuo wow, thanks!!!

**Comment by tiangexiang** [comment]
@ZhengyiLuo Hi, thanks for your response! It seems the SMPL params from https://github.com/mks0601/I2L-MeshNet_RELEASE cannot fit directly to the dataloader of this repo, how did you convert the formats? Or did you use a completely new dataloader for h36m? Thanks again!

**Comment by GloryyrolG** [comment]
> Hi,
> 
> Thanks a ton for the great work!
> 
> I am trying out the script to fit SMPL-X to 3D keypoints and are noticing a speed of about 40 secs per frame; This is rather slow even with parallelzation. Any suggestions?

Using 8 processes, it takes 400k * 40 / 8 / 3600 / 24 = 23 days...
