### ISSUE TITLE
Error pre-processing h36m data

### ISSUE THREAD

**Issue by nicolasugrinovic** [JiangWenPL/multiperson#9]
Error pre-processing data
`python h36m.py /datasets/Human36M/ ../../../mmdetection/data/h36m/rcnn --split=train`

```

Traceback (most recent call last):
  File "h36m.py", line 135, in <module>
    h36m_extract(args.dataset_path, args.out_path, split=args.split)
  File "h36m.py", line 131, in h36m_extract
    pickle.dump(data, f)
NameError: name 'data' is not defined
```

**Comment by with-twilight** [comment]
Hi,I have the same problem, can you share the solution?

**Comment by JiangWenPL** [comment]
Maybe you should replace `data` with `annotations` in [line 131](https://github.com/JiangWenPL/multiperson/blob/4d3dbae945e22bb1e270521b061a837976699685/misc/preprocess_datasets/full/h36m.py#L130)

**Comment by with-twilight** [comment]
OK，thank.
